name: Publish Documentation
description: 'Publish the documentation to hex.pm and github pages.'

inputs:
  github_token:
    description: 'The github token to use for committing'
    required: true

runs:
  using: composite
  steps:
    - uses: launchdarkly/gh-actions/actions/publish-pages@publish-pages-v1.0.1
      name: 'Publish to Github pages'
      with:
        docs_path: doc
        github_token: ${{ inputs.github_token }}
    - run: rebar3 hex docs
      shell: bash
