name: Publish Documentation
description: 'Publish the documentation to hex.pm and github pages.'
inputs:
  token:
    description: 'Hex.pm token.'
    required: true

runs:
  using: composite
  steps:
    - uses: launchdarkly/gh-actions/actions/publish-pages
      name: 'Publish to Github pages'
      with:
        docs_path: doc
    - name: Configure rebar3
      shell: bash
      run: ./.github/scripts/configure_rebar3.sh
      env:
        HEX_AUTH_TOKEN: ${{ inputs.token }}
    - run: rebar3 hex docs
      shell: bash
