name: Publish Package
description: 'Publish the package to Hex.pm'
inputs:
  dry_run:
    description: 'Is this a dry run. If so no package will be published.'
    required: true

runs:
  using: composite
  steps:
    - name: Publish Library
      shell: bash
      run: rebar3 hex publish
      # Do not publish a dry run.
      if: ${{ inputs.dry_run == 'false' }}
