version: 2

repo:
  public: erlang-server-sdk
  private: erlang-server-sdk-private

branches:
  - name: main
    description: 2.x
  - name: 1.x


jobs:
  - docker:
      image: erlang:24

documentation:
  title: LaunchDarkly Server-Side SDK for Erlang/Elixir
  gitHubPages: true

sdk:
  displayName: "Erlang (server-side)"
