# This is a composite to allow sharing these steps into other workflows.
# For instance it could be used by regular CI as well as the release process.

name: CI Workflow
description: "Shared CI workflow."
inputs:
  run_tests:
    description: "If true, run unit tests, otherwise skip them."
    required: false
    default: "true"
  github_token:
    description: "Github token used to access contract test harness."
    required: true

runs:
  using: composite
  steps:
    - run: make compile
      shell: bash
    - uses: supercharge/redis-github-action@ea9b21c6ecece47bd99595c532e481390ea0f044
    - run: make ci-tests
      shell: bash
    - uses: ./.github/actions/build-docs
    - run: make dialyze
      shell: bash
    - run: make build-contract-tests
      shell: bash
    - name: Start contract test service
      shell: bash
      run: make start-contract-test-service-bg
    - uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.1.0
      with:
        test_service_port: 8000
        token: ${{ inputs.github_token }}
        extra_params: '--skip-from=./test-service/testharness-suppressions.txt'
