name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-test:
    strategy:
      # We want to know the status of all OTP versions, not just if one of them fails.
      fail-fast: false
      matrix:
        versions:
          - { otp: "21.3.8.24", rebar: "0be8717a4ff5b4a0c3dcef5031fe9833197d861e" } # rebar 3.15.2
          - { otp: "25.3.2.19", rebar: "174fd9070195443d693d444ecd1f2b7aa91661fe" } # rebar 3.18.0
          - { otp: "27.3.2", rebar: "bde4b54248d16280b2c70a244aca3bb7566e2033" } # rebar 3.23.0

    runs-on: ubuntu-24.04
    name: Build and Test - ${{ matrix.versions.otp }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Erlang and rebar3
        uses: ./.github/actions/install-erlang
        with:
          otp_version: ${{ matrix.versions.otp }}
          rebar_version: ${{ matrix.versions.rebar }}

      - uses: ./.github/actions/ci
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          OTP_VER: ${{ matrix.versions.otp }}
