name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  build-test:
    strategy:
      matrix:
        otp: ['21.x', '22.x', '23.x', '24', '25.x']
    runs-on: 'ubuntu-latest'
    name: Build and Test - ${{ matrix.otp }}

    steps:
      - uses: erlef/setup-beam@v1
        with:
          version-type: loose
          otp-version: ${{ matrix.otp }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #If you only need the current version keep this.

      - uses: ./.github/actions/ci
