name: Build and Test

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md' #Do not need to run CI for markdown changes.
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  build-test:
    strategy:
      matrix:
        image: ['erlang:21', 'erlang:22', 'erlang:23', 'erlang:24', 'erlang:25']
    runs-on: 'ubuntu-latest'
    container: ${{ matrix.image }} 
    name: Build and Test - ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 #If you only need the current version keep this.

      - uses: ./.github/actions/ci
