name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-24.04
    permissions: 
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write

    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          fetch-depth: 0 # Full history is required for proper changelog generation

      - name: Install Erlang and rebar3
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: ./.github/actions/install-erlang

      - uses: ./.github/actions/configure-rebar
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - uses: ./.github/actions/ci
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - uses: ./.github/actions/build-docs
        if: ${{ steps.release.outputs.releases_created == 'true' }}

      - uses: ./.github/actions/publish
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          dry_run: false

      - uses: ./.github/actions/publish-docs
        if: ${{ steps.release.outputs.releases_created == 'true' }}
