name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

      - uses: erlef/setup-beam@v1
        if: ${{ steps.release.outputs.releases_created }}
        with:
          version-type: loose
          otp-version: 25.x
          rebar3-version: 3.18.0
          
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          fetch-depth: 0 #If you only need the current version keep this.

      - uses: ./.github/actions/configure-rebar
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/ci
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/build-docs
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/publish
        if: ${{ steps.release.outputs.releases_created }}
        with:
          dry_run: false

      - uses: ./.github/actions/publish-docs
        if: ${{ steps.release.outputs.releases_created }}
