name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-package:
    runs-on: ubuntu-24.04
    permissions: 
      id-token: write # Needed if using OIDC to get release secrets.
      contents: write # Contents and pull-requests are for release-please to make releases.
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: main

      - name: Install kerl
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          curl -s https://raw.githubusercontent.com/kerl/kerl/master/kerl > /tmp/kerl
          chmod a+x /tmp/kerl
          
      - name: Install Erlang OTP
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          # Install OTP 25.3.2.19
          OTP_VERSION="25.3.2.19"
          
          # Build and install Erlang
          /tmp/kerl build $OTP_VERSION $OTP_VERSION
          /tmp/kerl install $OTP_VERSION ~/otp/$OTP_VERSION
          . ~/otp/$OTP_VERSION/activate
          
          # Install rebar3
          mkdir -p ~/bin
          curl -s https://s3.amazonaws.com/rebar3/rebar3 -o ~/bin/rebar3
          chmod +x ~/bin/rebar3
          echo "~/bin" >> $GITHUB_PATH
          
          # Verify installation
          echo "Installed Erlang version:"
          erl -noshell -eval 'io:format("~s~n", [erlang:system_info(otp_release)]), halt().'
          echo "Installed rebar3 version:"
          rebar3 --version
          
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          fetch-depth: 0 #If you only need the current version keep this.

      - uses: ./.github/actions/configure-rebar
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/ci
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/build-docs
        if: ${{ steps.release.outputs.releases_created }}

      - uses: ./.github/actions/publish
        if: ${{ steps.release.outputs.releases_created }}
        with:
          dry_run: false

      - uses: ./.github/actions/publish-docs
        if: ${{ steps.release.outputs.releases_created }}
